"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'cg#p$g+j9tax!#a3cup@1$8obt2_+&k3q+pmu)5%asj6yjpkag')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool( os.environ.get('DJANGO_DEBUG', True) )

ALLOWED_HOSTS = [
    'api.cincosas.com', 
    'www.api.cincosas.com', 
    '192.168.79.11', 
    '127.0.0.1', 
    'localhost'
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True  # Permite envío de cookies entre dominios

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "https://frontend.cincosas.com",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "https://frontend.cincosas.com",
]

# Configuración de cookies seguras
SECURE_COOKIE = not DEBUG  # Solo HTTPS en producción
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = 'Lax'  # Protección contra CSRF
CSRF_COOKIE_HTTPONLY = False  # Necesario para leer el token en el frontend

if DEBUG:
    CSRF_COOKIE_SAMESITE = 'Lax'
else:
    CSRF_COOKIE_SAMESITE = 'None'

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party
    "rest_framework",
    "corsheaders",
    'drf_spectacular',
    
    # Local apps
    'apps.authentication',
    'apps.common',
    'apps.security',
    'apps.operaciones',
    'apps.empleados',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "apps.authentication.authentication.jwt_authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'App Cinco API',
    'DESCRIPTION': 'Documentación de endpoints - App Cinco',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SECURITY': [{'BearerAuth': []}],
    'COMPONENTS': {
        'securitySchemes': {
            'BearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        }
    }
}

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # },
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('BD_NAME', 'db_cincosas'),
        'USER': os.environ.get('BD_USER', 'root'),
        'PASSWORD': os.environ.get('BD_PASSWORD', ''),
        'HOST': os.environ.get('BD_HOST', '127.0.0.1'),
        'PORT': os.environ.get('BD_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
        }
    },
    'azul': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_AZUL_NAME', 'cinco-api'),
        'USER': os.environ.get('DB_AZUL_USER', 'root'),
        'PASSWORD': os.environ.get('DB_AZUL_PASSWORD', ''),
        'HOST': os.environ.get('DB_AZUL_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DB_AZUL_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
        }
    }
}

DATABASE_ROUTERS = ['config.db_router.MultiDBRouter']


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-CO'
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
# STATIC_URL = '/home/admcinco/app_cinco/backend/static/'
STATIC_URL = os.getenv('BASE_PATH', '') + 'static/'
# STATIC_ROOT = '/home/admcinco/app_cinco/backend/static'
STATIC_ROOT = os.getenv('BASE_PATH', '') + 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#SECURE_HSTS_SECONDS = 31536000
#SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True  # Solo si estás seguro de que todo es HTTPS
#SECURE_SSL_REDIRECT = True
#SESSION_COOKIE_SECURE = True
#CSRF_COOKIE_SECURE = True