# Generated by Django 5.2.10 on 2026-09-11 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0005_make_optional_front_fields_optional_in_backend'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaTecnicoRegistro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=50, unique=True)),
                ('sede', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('carpeta', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(default='1', max_length=10)),
                ('edit', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_edit', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agenda_trabajos_cinco_registro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgendaTrabajo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=50)),
                ('sede', models.CharField(blank=True, max_length=50, null=True)),
                ('yyyy', models.CharField(max_length=10)),
                ('mes', models.CharField(max_length=10)),
                ('carpeta', models.CharField(blank=True, max_length=100, null=True)),
                ('datos', models.JSONField(blank=True, null=True)),
                ('edit', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_edit', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agenda_trabajos_cinco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InfraestructuraParametros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('carpeta', models.CharField(blank=True, max_length=100, null=True)),
                ('parametros_agenda', models.JSONField(blank=True, null=True)),
                ('edit', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_edit', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'infraestructura_parametros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(help_text='Fecha inicial del agendamiento')),
                ('fecha_fin', models.DateField(help_text='Fecha final del agendamiento')),
                ('sede', models.CharField(db_index=True, help_text='Sede operativa (medellin, monteria, etc.)', max_length=50)),
                ('color_hex', models.CharField(default='#A55BD8', help_text='Color corporativo visual en el calendario', max_length=7)),
                ('observacion', models.TextField(blank=True, help_text='Notas u observaciones del agendamiento', null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actividad', models.ForeignKey(db_column='actividad_id', help_text='Actividad / OT programada en la agenda', on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='operaciones.actividad')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendas_creadas', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendas_eliminadas', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(db_column='responsable_id', help_text='Usuario / Técnico asignado para ejecutar la labor', on_delete=django.db.models.deletion.PROTECT, related_name='agendas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendas_actualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operaciones_agenda',
                'ordering': ['fecha_inicio', 'id'],
                'indexes': [models.Index(fields=['sede', 'fecha_inicio', 'fecha_fin', 'is_deleted'], name='idx_agenda_sede_fechas'), models.Index(fields=['responsable', 'fecha_inicio', 'fecha_fin'], name='idx_agenda_responsable_fechas'), models.Index(fields=['actividad', 'is_deleted'], name='idx_agenda_actividad_del')],
            },
        ),
    ]
