# Generated by Django 5.2.10 on 2026-08-26 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la aplicación externa', max_length=255)),
                ('key_hash', models.CharField(db_index=True, max_length=128, unique=True)),
                ('prefix', models.CharField(db_index=True, help_text='Prefijo visible de la key', max_length=8)),
                ('is_active', models.BooleanField(default=True, help_text='Si la API Key está activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('allowed_ips', models.TextField(blank=True, help_text='IPs permitidas separadas por coma')),
                ('rate_limit', models.IntegerField(default=1000, help_text='Requests por hora')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha de expiración', null=True)),
                ('description', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'db_table': 'api_keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.IntegerField()),
                ('can_read', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_insert', models.BooleanField(default=False)),
                ('can_import', models.BooleanField(default=False)),
                ('can_manual', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_user_permissions',
                'unique_together': {('user', 'menu_id')},
            },
        ),
    ]
