# Generated by Django 5.2.10 on 2026-08-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoFirmaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmante_nombre', models.CharField(default='FARAY MONSALVE URREGO', max_length=255)),
                ('firmante_cargo', models.CharField(default='Dirección Gestión Humana', max_length=255)),
                ('firma_imagen_nombre', models.CharField(default='Firma-RRHH.png', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'certificado_firma_config',
            },
        ),
    ]
