# Generated by Django 5.2.10 on 2026-09-25 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smudetallecapex',
            name='spt_resistividad',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='accion_adicion_refrigerante',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='accion_ajuste_controles',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='accion_alineacion_poleas',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='accion_cambio_compresor',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='accion_cambio_correas_filtros',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='accion_cambio_electronicos',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='accion_cambio_filtros_secado',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='accion_estado_drenajes',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='accion_limpieza_serpentines',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='accion_lubricacion',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='accion_otras_reparaciones',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='cond_aislamiento',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='cond_amp_l1',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='cond_amp_l2',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='cond_amp_l3',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='cond_marca',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='cond_modelo',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='cond_nivel_aceite',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='cond_presion_descarga',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='cond_presion_succion',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='cond_refrigerante',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='cond_serial',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='cond_tipo',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='cond_vl1',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='cond_vl2',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='cond_vl3',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='firma_responsable',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='manejadora_aislamiento',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='manejadora_alimentacion',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='manejadora_blower',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='manejadora_correa',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='manejadora_corriente',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='manejadora_filtro',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='manejadora_marca',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='manejadora_modelo',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='manejadora_motor_marca',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='manejadora_motor_serial',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='manejadora_tipo',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='manejadora_voltaje',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='vent_diametro_aspas',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='vent_diametro_eje',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='vent_marca',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='vent_modelo',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='vent_serial',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='vent_temp_entrada',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoaa',
            name='vent_temp_salida',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoplanta',
            name='bateria_cantidad',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoplanta',
            name='bateria_capacidad',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoplanta',
            name='bateria_estado',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoplanta',
            name='bateria_estado_cargador',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoplanta',
            name='bateria_tipo',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoplanta',
            name='bateria_voltaje',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoplanta',
            name='dimensionamiento_capacidad_amp',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoplanta',
            name='dimensionamiento_carga_demanda',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoplanta',
            name='dimensionamiento_porc_carga',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoplanta',
            name='equipo_admision_aire',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoplanta',
            name='equipo_capacidad_derrateo',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoplanta',
            name='equipo_capacidad_kva',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoplanta',
            name='equipo_capacidad_kw',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoplanta',
            name='equipo_derrateo',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoplanta',
            name='equipo_frecuencia_hz',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoplanta',
            name='equipo_horas_trabajo',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoplanta',
            name='equipo_marca',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoplanta',
            name='equipo_modelo',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoplanta',
            name='equipo_rpm',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoplanta',
            name='equipo_serial',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoplanta',
            name='equipo_velocidad_motor',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoplanta',
            name='generador_marca',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoplanta',
            name='generador_modelo',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoplanta',
            name='generador_serial',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoplanta',
            name='motor_marca',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoplanta',
            name='motor_modelo',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoplanta',
            name='motor_presion_aceite',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoplanta',
            name='motor_serial',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoplanta',
            name='motor_temp_aceite',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoplanta',
            name='motor_temp_refrigerante',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoplanta',
            name='param_amp_l1',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoplanta',
            name='param_amp_l2',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoplanta',
            name='param_amp_l3',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoplanta',
            name='param_vac_l1_l2',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoplanta',
            name='param_vac_l1_l3',
        ),
        migrations.RemoveField(
            model_name='smudetallepreventivoplanta',
            name='param_vac_l2_l3',
        ),
        migrations.AddField(
            model_name='smuactividad',
            name='empresa',
            field=models.CharField(blank=True, help_text='Empresa aliada/contratista que ejecuta la actividad', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='smuactividadmaterial',
            name='comentarios',
            field=models.TextField(blank=True, help_text='Comentarios de proceso del ítem (CAPEX insumos)', null=True),
        ),
        migrations.AddField(
            model_name='smuactividadmaterial',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción de la actividad de mano de obra (CAPEX tipología 3 y 5)', null=True),
        ),
        migrations.AddField(
            model_name='smudetallecapex',
            name='descripcion_general_actividades',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smudetallecapex',
            name='matricula_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smudetallecapex',
            name='matricula_nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='smudetallecapex',
            name='matricula_numero',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='smudetallecapex',
            name='otras_actividades_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smudetallecapex',
            name='otras_actividades_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smudetallecapex',
            name='otras_actividades_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smudetallepreventivoplanta',
            name='cambio_aceite',
            field=models.CharField(blank=True, choices=[('SÍ', 'SÍ'), ('NO', 'NO'), ('N/A', 'N/A')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='smudetallepreventivoplanta',
            name='cambio_baterias',
            field=models.CharField(blank=True, choices=[('SÍ', 'SÍ'), ('NO', 'NO'), ('N/A', 'N/A')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='smudetallepreventivoplanta',
            name='cambio_filtros_aceite',
            field=models.CharField(blank=True, choices=[('SÍ', 'SÍ'), ('NO', 'NO'), ('N/A', 'N/A')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='smudetallepreventivoplanta',
            name='cambio_filtros_aire',
            field=models.CharField(blank=True, choices=[('SÍ', 'SÍ'), ('NO', 'NO'), ('N/A', 'N/A')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='smudetallepreventivoplanta',
            name='cambio_filtros_combustible',
            field=models.CharField(blank=True, choices=[('SÍ', 'SÍ'), ('NO', 'NO'), ('N/A', 'N/A')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='smudetallepreventivoplanta',
            name='cambio_mangueras_precalentador',
            field=models.CharField(blank=True, choices=[('SÍ', 'SÍ'), ('NO', 'NO'), ('N/A', 'N/A')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='smudetallepreventivoplanta',
            name='cambio_refrigerante',
            field=models.CharField(blank=True, choices=[('SÍ', 'SÍ'), ('NO', 'NO'), ('N/A', 'N/A')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='smudetallepreventivoplanta',
            name='estructura',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='smudetallepreventivoplanta',
            name='fecha_elaboracion_informe',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smudetallepreventivoplanta',
            name='observaciones_filtracion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smudetallepreventivoplanta',
            name='observaciones_pruebas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smudetallepreventivoplanta',
            name='orden_trabajo_tas',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='smudetallepreventivoplanta',
            name='plan_mejora_estado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smudetallepreventivoplanta',
            name='prueba_con_carga',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NO OK', 'NO OK'), ('N/A', 'N/A')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='smudetallepreventivoplanta',
            name='prueba_planta_forzada',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NO OK', 'NO OK'), ('N/A', 'N/A')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='smudetallepreventivoplanta',
            name='prueba_transferencia_automatica',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NO OK', 'NO OK'), ('N/A', 'N/A')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='smudetallepreventivoplanta',
            name='prueba_vacio',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NO OK', 'NO OK'), ('N/A', 'N/A')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='smuactividadmaterial',
            name='tipo_registro',
            field=models.CharField(choices=[('inventario_capex', 'Inventario CAPEX'), ('material_emergencia', 'Material Emergencia'), ('material_correctivo', 'Material Correctivo'), ('mano_obra_capex', 'Mano de Obra CAPEX'), ('inventario_preventivo', 'Inventario Preventivo'), ('mano_obra_preventivo', 'Mano de Obra Preventiva')], max_length=50),
        ),
        migrations.AlterField(
            model_name='smudetallepreventivoplantachecklist',
            name='componente',
            field=models.CharField(help_text='conexiones, abrazaderas, tanque, nivel_aceite, etc. (se usa el texto completo de la ficha oficial)', max_length=255),
        ),
        migrations.CreateModel(
            name='SmuActividadCertificado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=120, null=True)),
                ('categoria', models.CharField(blank=True, max_length=120, null=True)),
                ('ruta_certificado', models.CharField(blank=True, max_length=350, null=True)),
                ('ruta_foto_sitio', models.CharField(blank=True, help_text='Foto del certificado en sitio', max_length=350, null=True)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(db_column='actividad_id', on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='smu.smuactividad')),
            ],
            options={
                'db_table': 'smu_actividad_certificados',
                'ordering': ['orden', 'id'],
                'indexes': [models.Index(fields=['actividad'], name='idx_certificados_actividad')],
            },
        ),
        migrations.CreateModel(
            name='SmuActividadCierreFirma',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('tecnico', 'Técnico'), ('revisor', 'Revisor'), ('entrega', 'Responsable de entrega'), ('aprobador', 'Aprobador')], max_length=30)),
                ('nombre', models.CharField(max_length=150)),
                ('cedula', models.CharField(blank=True, max_length=30, null=True)),
                ('cargo', models.CharField(blank=True, max_length=120, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('ruta_firma', models.CharField(blank=True, help_text='Ruta de la imagen de la firma', max_length=350, null=True)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(db_column='actividad_id', on_delete=django.db.models.deletion.CASCADE, related_name='firmas_cierre', to='smu.smuactividad')),
            ],
            options={
                'db_table': 'smu_actividad_cierre_firmas',
                'ordering': ['orden', 'id'],
                'indexes': [models.Index(fields=['actividad'], name='idx_firmas_cierre_actividad')],
            },
        ),
        migrations.CreateModel(
            name='SmuDetalleCapexSptFila',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('distancia', models.CharField(blank=True, max_length=60, null=True)),
                ('medida_ohmio', models.CharField(blank=True, max_length=60, null=True)),
                ('resistividad', models.CharField(blank=True, max_length=60, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(db_column='actividad_id', on_delete=django.db.models.deletion.CASCADE, related_name='spt_filas', to='smu.smuactividad')),
            ],
            options={
                'db_table': 'smu_detalle_capex_spt_filas',
                'ordering': ['orden', 'id'],
                'indexes': [models.Index(fields=['actividad'], name='idx_spt_filas_actividad')],
            },
        ),
        migrations.CreateModel(
            name='SmuPreventivoAaAccion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(help_text='limpieza_serpentines, ajuste_elementos_control, adicion_refrigerante, estado_drenajes, lubricacion_componentes, cambio_filtros_secado, alineacion_poleas, cambio_componentes_electronicos, cambio_compresor, cambio_correas_filtros, otras_reparaciones', max_length=60)),
                ('valor', models.CharField(choices=[('SI', 'SÍ'), ('NO', 'NO'), ('NA', 'N/A'), ('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo')], max_length=20)),
                ('orden', models.PositiveSmallIntegerField(default=1, help_text='Fila del formulario (1 por unidad AA registrada)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(db_column='actividad_id', on_delete=django.db.models.deletion.CASCADE, related_name='aa_acciones', to='smu.smuactividad')),
            ],
            options={
                'db_table': 'smu_preventivo_aa_acciones',
                'ordering': ['orden', 'id'],
                'indexes': [models.Index(fields=['actividad'], name='idx_aa_acciones_act'), models.Index(fields=['clave'], name='idx_aa_acciones_clave')],
            },
        ),
        migrations.CreateModel(
            name='SmuPreventivoAaCompresor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('serial', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=80, null=True)),
                ('refrigerante', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('aislamiento_electrico', models.CharField(blank=True, max_length=50, null=True)),
                ('presion_succion', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('presion_descarga', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('nivel_aceite', models.CharField(blank=True, max_length=50, null=True)),
                ('vl1', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('vl2', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('vl3', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('amp_l1', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('amp_l2', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('amp_l3', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(db_column='actividad_id', on_delete=django.db.models.deletion.CASCADE, related_name='aa_compresores', to='smu.smuactividad')),
            ],
            options={
                'db_table': 'smu_preventivo_aa_compresores',
                'ordering': ['orden', 'id'],
                'indexes': [models.Index(fields=['actividad'], name='idx_aa_compresores_act')],
            },
        ),
        migrations.CreateModel(
            name='SmuPreventivoAaCondensadora',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('serial', models.CharField(blank=True, max_length=100, null=True)),
                ('temperatura_entrada', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('temperatura_salida', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('diametro_eje', models.CharField(blank=True, max_length=50, null=True)),
                ('diametro_aspas', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(db_column='actividad_id', on_delete=django.db.models.deletion.CASCADE, related_name='aa_condensadoras', to='smu.smuactividad')),
            ],
            options={
                'db_table': 'smu_preventivo_aa_condensadoras',
                'ordering': ['orden', 'id'],
                'indexes': [models.Index(fields=['actividad'], name='idx_aa_condensadoras_act')],
            },
        ),
        migrations.CreateModel(
            name='SmuPreventivoAaManejadora',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=80, null=True)),
                ('tipo_filtro', models.CharField(blank=True, max_length=80, null=True)),
                ('tipo_correa', models.CharField(blank=True, max_length=80, null=True)),
                ('marca_motor', models.CharField(blank=True, max_length=100, null=True)),
                ('alimentacion_ac', models.CharField(blank=True, max_length=50, null=True)),
                ('voltaje', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('corriente', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('aislamiento', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('serial_motor', models.CharField(blank=True, max_length=100, null=True)),
                ('dimensiones_blower', models.CharField(blank=True, max_length=80, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(db_column='actividad_id', on_delete=django.db.models.deletion.CASCADE, related_name='aa_manejadoras', to='smu.smuactividad')),
            ],
            options={
                'db_table': 'smu_preventivo_aa_manejadoras',
                'ordering': ['orden', 'id'],
                'indexes': [models.Index(fields=['actividad'], name='idx_aa_manejadoras_act')],
            },
        ),
        migrations.CreateModel(
            name='SmuPreventivoPlanta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('nombre_unidad', models.CharField(blank=True, max_length=120, null=True)),
                ('equipo_marca', models.CharField(blank=True, max_length=100, null=True)),
                ('equipo_modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('equipo_serial', models.CharField(blank=True, max_length=100, null=True)),
                ('equipo_velocidad_motor', models.CharField(blank=True, max_length=80, null=True)),
                ('equipo_admision_aire', models.CharField(blank=True, max_length=80, null=True)),
                ('equipo_rpm', models.PositiveIntegerField(default=0)),
                ('equipo_horas_trabajo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('equipo_frecuencia_hz', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('equipo_capacidad_kva', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('equipo_capacidad_kw', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('equipo_derrateo', models.CharField(blank=True, max_length=80, null=True)),
                ('equipo_capacidad_derrateo', models.CharField(blank=True, max_length=80, null=True)),
                ('motor_marca', models.CharField(blank=True, max_length=100, null=True)),
                ('motor_modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('motor_serial', models.CharField(blank=True, max_length=100, null=True)),
                ('motor_presion_aceite', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('motor_temp_aceite', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('motor_temp_refrigerante', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('generador_marca', models.CharField(blank=True, max_length=100, null=True)),
                ('generador_modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('generador_serial', models.CharField(blank=True, max_length=100, null=True)),
                ('generador_temp_ambiente', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('bateria_tipo', models.CharField(blank=True, max_length=80, null=True)),
                ('bateria_estado', models.CharField(blank=True, max_length=50, null=True)),
                ('bateria_estado_cargador', models.CharField(blank=True, max_length=50, null=True)),
                ('bateria_voltaje', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('bateria_capacidad', models.CharField(blank=True, max_length=50, null=True)),
                ('bateria_cantidad', models.PositiveSmallIntegerField(default=0)),
                ('param_vac_l1_l2', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('param_vac_l1_l3', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('param_vac_l2_l3', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('param_amp_l1', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('param_amp_l2', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('param_amp_l3', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('dimensionamiento_capacidad_amp', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('dimensionamiento_carga_demanda', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('dimensionamiento_porc_carga', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(db_column='actividad_id', on_delete=django.db.models.deletion.CASCADE, related_name='plantas', to='smu.smuactividad')),
            ],
            options={
                'db_table': 'smu_preventivo_plantas',
                'ordering': ['orden', 'id'],
                'indexes': [models.Index(fields=['actividad'], name='idx_plantas_actividad')],
            },
        ),
        migrations.CreateModel(
            name='SmuPreventivoPlantaHallazgo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(db_column='actividad_id', on_delete=django.db.models.deletion.CASCADE, related_name='hallazgos_planta', to='smu.smuactividad')),
            ],
            options={
                'db_table': 'smu_preventivo_planta_hallazgos',
                'ordering': ['orden', 'id'],
                'indexes': [models.Index(fields=['actividad'], name='idx_hallazgos_planta_act')],
            },
        ),
    ]
