# Generated by Django 5.2.10 on 2026-09-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smu', '0002_remove_smudetallecapex_spt_resistividad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smuactividad',
            name='categoria_criticidad',
            field=models.CharField(blank=True, help_text='Criticidad del reporte (ej: 1. ALTA) - formulario estándar', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='smuactividadevidencia',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción o comentario que el usuario escribe sobre la foto', null=True),
        ),
        migrations.AddField(
            model_name='smuactividadmaterial',
            name='origen_material',
            field=models.CharField(blank=True, help_text='Proveedor/origen del material (ej: CINCO SAS) - formulario estándar', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='smudetallefallaintervencion',
            name='cambio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='smudetallefallaintervencion',
            name='detalles_plano',
            field=models.TextField(blank=True, help_text='Detalles del plano / croquis de la intervención - formulario estándar', null=True),
        ),
        migrations.AddField(
            model_name='smudetallefallaintervencion',
            name='reinstalacion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='smudetallefallaintervencion',
            name='reparacion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
