# Generated by Django 5.2.10 on 2026-10-05 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0005_make_optional_front_fields_optional_in_backend'),
        ('smu', '0003_smuactividad_categoria_criticidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='smuactividad',
            name='actividad_operaciones',
            field=models.ForeignKey(blank=True, db_column='operacion_actividad_id', help_text='Vínculo con la orden de trabajo de operaciones central', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smu_actividades', to='operaciones.actividad'),
        ),
        migrations.AddField(
            model_name='smuactividad',
            name='responsable',
            field=models.ForeignKey(blank=True, db_column='responsable_usuario_id', help_text='Usuario central autenticado responsable del reporte', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actividades_responsable_smu', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smuactividadtecnico',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='usuario_id', help_text='Usuario central del técnico', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tecnico_actividades_smu', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='smuactividad',
            name='nombre_estacion',
            field=models.CharField(help_text='Snapshot histórico / nombre de estación', max_length=150),
        ),
        migrations.AlterField(
            model_name='smuactividadmaterial',
            name='comprado_operario',
            field=models.BooleanField(default=False, help_text='1 si fue comprado directamente en campo (fuera de catálogo)'),
        ),
        migrations.CreateModel(
            name='SmuEstacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_sitio', models.CharField(db_index=True, help_text='Nombre único oficial del sitio / estación', max_length=150, unique=True)),
                ('regional', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                ('departamento', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                ('municipio', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                ('zona', models.CharField(blank=True, max_length=80, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('tipo_estacion', models.CharField(blank=True, max_length=80, null=True)),
                ('tipo_sitio', models.CharField(blank=True, max_length=80, null=True)),
                ('site_owner', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria_criticidad', models.CharField(blank=True, help_text='Criticidad de la estación (ej: 1. ALTA, 2. MEDIA, 3. BAJA)', max_length=50, null=True)),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='Estado de disponibilidad operativa de la estación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'smu_estaciones',
                'ordering': ['nombre_sitio'],
                'indexes': [models.Index(fields=['regional', 'departamento'], name='idx_smu_estaciones_reg_dep'), models.Index(fields=['tipo_estacion'], name='idx_smu_estaciones_tipo_est'), models.Index(fields=['activo'], name='idx_smu_estaciones_activo')],
            },
        ),
        migrations.AddField(
            model_name='smuactividad',
            name='estacion',
            field=models.ForeignKey(blank=True, db_column='estacion_id', help_text='Clave foránea con la tabla maestra de estaciones', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='smu.smuestacion'),
        ),
        migrations.CreateModel(
            name='SmuMatrizLpu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_sap', models.CharField(db_index=True, help_text='Código SAP oficial único del material / ítem', max_length=60, unique=True)),
                ('codigo_liquidacion', models.CharField(blank=True, db_index=True, help_text='Código auxiliar para procesos de liquidación', max_length=60, null=True)),
                ('texto_sap', models.CharField(help_text='Descripción o texto oficial del ítem según SAP', max_length=255)),
                ('descripcion', models.TextField(blank=True, help_text='Detalle o alcance extendido del ítem', null=True)),
                ('unidad_medida', models.CharField(blank=True, help_text='Unidad de medida (ej: UN, M, GL, HORA)', max_length=30, null=True)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0.0, help_text='Precio o valor unitario vigente', max_digits=14)),
                ('tipo_registro', models.CharField(blank=True, help_text='Clasificación LPU (ej: inventario_capex, mano_obra, preventivo, etc.)', max_length=50, null=True)),
                ('fecha_vigencia_inicio', models.DateField(blank=True, help_text='Fecha inicial de validez del precio/tarifa', null=True)),
                ('fecha_vigencia_fin', models.DateField(blank=True, help_text='Fecha final de validez del precio/tarifa', null=True)),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='Indica si el ítem está activo en el catálogo vigente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'smu_matriz_lpu',
                'ordering': ['codigo_sap'],
                'indexes': [models.Index(fields=['codigo_liquidacion'], name='idx_smu_lpu_cod_liq'), models.Index(fields=['tipo_registro'], name='idx_smu_lpu_tipo_reg'), models.Index(fields=['activo'], name='idx_smu_lpu_activo')],
            },
        ),
        migrations.AddField(
            model_name='smuactividadmaterial',
            name='material_lpu',
            field=models.ForeignKey(blank=True, db_column='material_lpu_id', help_text='Vínculo con el catálogo oficial maestro LPU', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usos_actividad', to='smu.smumatrizlpu'),
        ),
    ]
